### ISSUE TITLE
error :hello_video.bin No such file or directory

### ISSUE THREAD

**Issue by MuhammadAsghar** [raspberrypilearning/demo-programs#7]
I am trying to compile hello_video.bin demo of raspberry pi. but when i compile according to instruction i got this error and also when i list directory i can not find any file of .bin extension. i have four files in hello_video folder which are hello_video.c test.h264 README and Makefile.

**Comment by lawsie** [comment]
Hi Muhammad. That looks like you haven't compiled the demos. Did you run the rebuild.sh script in the first step of the guide and then test with the hello world script?

**Comment by MuhammadAsghar** [comment]
Thank you lawsie
        I first run rebuild.sh and then tried it but the problem remains same

**Comment by lawsie** [comment]
Were you able to run the first Hello World test script?

**Comment by lawsie** [comment]
I'm going to close this issue as I haven't heard from you in a while, but feel free to reopen it with an update :)
